storage:
  ai:
    account_name: "YOUR_AI_ACCOUNT_NAME"
    account_key: "YOUR_AI_ACCOUNT_KEY"
    account_str: "DefaultEndpointsProtocol=https;AccountName=YOUR_AI_ACCOUNT_NAME;AccountKey=YOUR_AI_ACCOUNT_KEY;EndpointSuffix=core.windows.net"
    log_storage: log
    preprosessed_storage: preprocessed-data
  web:
    account_name: "YOUR_WEB_ACCOUNT_NAME"
    account_key: "YOUR_WEB_ACCOUNT_KEY"
    account_str: "DefaultEndpointsProtocol=https;AccountName=YOUR_WEB_ACCOUNT_NAME;AccountKey=YOUR_WEB_ACCOUNT_KEY;EndpointSuffix=core.windows.net"
    raw_storage: upload
    raw_folder: qas
    queue_storage: wkms-trigger-queue

mysql:
  host: "YOUR_MYSQL_HOST"
  port: 3306
  user: "YOUR_MYSQL_USER"
  password: "YOUR_MYSQL_PASSWORD"
  database: "YOUR_MYSQL_DATABASE"

di:
  endpoint: "YOUR_DI_ENDPOINT"
  key: "YOUR_DI_KEY"

openai:
  api_base: "YOUR_OPENAI_API_BASE"
  api_key: "YOUR_OPENAI_API_KEY"
