# Python Function App to Linux on Azure
# Build a Python function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - dev
      - prod


variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'wkmsdev-sc'
  

  # Function app name
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
    functionAppName: 'wkms-eastasia-dev-api'
    # functionAppName: 'wkms-eastus-api'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/prod') }}:
    functionAppName: 'wkms-eastasia-prod-api'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/functions'
  # debDirectory: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Woongjin Pipelines'
      #vmImage: $(vmImageName)

    steps:
    - bash: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
        fi
      workingDirectory: $(workingDirectory)
      displayName: 'Build extensions'
    # - script: |
    #     export PATH="/usr/local/bin/python3.11:$PATH"
    #     python3 --version
    #   displayName: 'Set PATH and Check Python Version'

    #- task: UsePythonVersion@0
    #  displayName: 'Use Python 3.11.8'
    #  inputs:
    #    versionSpec: 3.11.8 # Functions V2 supports Python 3.11 as of today

    # - bash: |
    #     tar -xvf  ../LibreOffice_24.8.4_Linux_x86-64_deb.tar.gz
    #   workingDirectory: $(workingDirectory)
    #   displayName: 'unzip tar.gz'

    - bash: |
        sudo apt-get install -y libreoffice
      workingDirectory: $(workingDirectory)
      displayName: 'install apt packages'

    - bash: |
        pip3 install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      name: 'Woongjin Pipelines'
      #vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@2
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'